// Import all components that we want to test
import './components/basic-bindings'
import './components/subscribe-without-args'
import './components/subscribe-wrong-type'
import './components/subscribe-unattached'
import './components/no-shadow-root'
import './components/closed-shadow-root'
import './components/bind-type'
import './components/state-key-not-found'
import './components/state-key-not-found-deep'
import './components/state-key-type'
import './components/state-key-invalid'
